[project]
name = "dp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gym-pusht==0.1.6",
    "zarr==2.18.3",
    "wandb==0.24.1",
]
